// Generated by CoffeeScript 1.7.1
angular.module('fs.video-playlist', []);

angular.module('fs.video-playlist').directive('promoteVideo', function($compile) {
  return {
    restrict: 'A',
    link: function(scope) {}
  };
});
